### ISSUE TITLE
Remate final

### ISSUE THREAD

**Issue by nasivuela** [Adalab/d-s1-evaluacion-intermedia-mariavioleta1417#8]
Buen trabajo @mariavioleta1417 !!

¿Pulimos un par de detalles y le ponemos la guinda?

1. Si te pones las gafas de maquetadora veras que en la versión tablet la cabecera tiene un espacio inferior que hace que parezca que el contenido no está centrado verticalmente.

2. Ojo con abusar del selector estrella. `.menu-item > *`. Esto mismo podriamos hacerlo poniendole una clase extra y común a los dos enlaces del menú.  Así si mañana detro de .menú-item tambien hay por ejemplo un span con un icono, no se verá afectado por esa regla de la estrella.

A por ello, que tiene muy buena pinta ;)

**Comment by mariavioleta1417** [comment]
la cabecera tenía por ahi un margin 13px, se lo he quitado , creo que ahora se ve mejor.
lo de la * también está arreglado.

**Comment by nasivuela** [comment]
Ole!

![](https://media.giphy.com/media/TEFplLVRDMWBi/giphy.gif)
